# Generated by Django 5.2.8 on 2025-12-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_device_type_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(default=0.5),
        ),
    ]
