version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mosquitto
    networks:
      - iothive-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - iothive-network

  celery:
    build:
      context: ./backend
    command: celery -A iothive worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - mosquitto
    networks:
      - iothive-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-broker
    ports:
      - "1883:1883"  # Standard MQTT port
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Configuration file for Mosquitto
      - mosquitto-data:/mosquitto/data  # Persistent data storage
      - mosquitto-log:/mosquitto/log    # Persistent log storage
    networks:
      - iothive-network  # Ensure all services communicate via the same network
  client:
    build: ./mqtt-client
    container_name: mqtt-client
    depends_on:
      - mosquitto
    stdin_open: true
    tty: true
    networks:
      - iothive-network  # Ensure all services communicate via the same network
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - iothive-network
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: iot_org
      DOCKER_INFLUXDB_INIT_BUCKET: iot_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: iot_token

  telegraf:
    image: telegraf:1.29
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - iothive-network
    depends_on:
      - mosquitto
      - influxdb

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - iothive-network
    depends_on:
      - influxdb


#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend

volumes:
  mosquitto-data:   # Persistent volume for Mosquitto data
  mosquitto-log:    # Persistent volume for Mosquitto logs
  influxdb_data:
  grafana_data:

networks:
  iothive-network:
    driver: bridge
