# Generated by Django 5.2.1 on 2025-06-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
