# Generated by Django 5.2.6 on 2025-09-28 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('expected_state', models.BooleanField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('crit', 'Critical')], default='warn', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alarm_rules', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rules', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=240)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('crit', 'Critical')], default='warn', max_length=10)),
                ('observed_value', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to='devices.device')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='devices.alarmrule')),
            ],
        ),
        migrations.AddIndex(
            model_name='alarmrule',
            index=models.Index(fields=['device', 'active'], name='devices_ala_device__6b6e57_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['device', 'is_active'], name='devices_ala_device__d54784_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['severity', 'is_active'], name='devices_ala_severit_714e71_idx'),
        ),
    ]
