# Generated by Django 5.2.6 on 2025-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alarmrule_alarmevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_rating_watts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='current_power_watts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='target_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='current_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
