# Generated by Django 5.2.8 on 2025-12-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_power_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('light', 'Light'), ('thermostat', 'Thermostat'), ('switch', 'Switch'), ('dishwasher', 'Dishwasher'), ('washing_machine', 'Washing Machine'), ('dryer', 'Dryer'), ('oven', 'Oven'), ('microwave', 'Microwave'), ('kettle', 'Kettle'), ('gas', 'Gas Range'), ('fridge', 'Fridge'), ('tv', 'TV')], max_length=50),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('alarm_rule', 'Alarm Rule'), ('control', 'Control Suggestion')], default='alarm_rule', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('crit', 'Critical')], default='warn', max_length=10)),
                ('target_min_value', models.FloatField(blank=True, null=True)),
                ('target_max_value', models.FloatField(blank=True, null=True)),
                ('target_expected_state', models.BooleanField(blank=True, null=True)),
                ('target_severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('crit', 'Critical')], default='warn', max_length=10)),
                ('target_note', models.CharField(blank=True, default='', max_length=200)),
                ('acknowledged', models.BooleanField(default=False)),
                ('implemented', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'dismissed'], name='devices_rec_device__5e83ca_idx')],
            },
        ),
    ]
